image:
  file: .gitpod.Dockerfile
tasks:
  - name: Install Languages
    before: sed -i -e 's/sdkman_auto_answer=false/sdkman_auto_answer=true/g' /home/gitpod/.sdkman/etc/config
    command: sdk install java 8.0.302-open \
             && sdk install scala 2.12.15
  - name: Moving directories
    before: chmod +rwx initScript.sh
    init: echo 'Moving directories. Please wait'
    command: ./initScript.sh
