image:
  file: .gitpod.Dockerfile
tasks:
  - name: Initializing
    before: chmod +rwx initScript.sh
    command: ./initScript.sh \
             && sdk install java 8.0.362-tem \
             && sdk install scala 2.12.15
